# Default Netlify configuration for a Vite project.

[build]
  # This command executes the "build" script from your package.json file.
  command = "npm run build"

  # This is the directory that contains the production-ready files
  # after the build command has been executed.
  publish = "dist"

[build.environment]
  # It is good practice to specify a Node.js version to ensure
  # your build environment is consistent.
  NODE_VERSION = "18"